import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";
import Footer from "./components/shared/Footer";
import Navbar from "./components/shared/navbar/Navbar";
import NavLinks from "./components/shared/navbar/NavLinks";

const notoBengali = Noto_Sans_Bengali({
  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoBengali.className}h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar>
          <NavLinks></NavLinks>
        </Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
